import React from 'react';
import { Edit3, Film, Plus, Search, Trash2, Tv2, X } from 'lucide-react';
import './vod.css';

const emptyMovie={title:'',description:'',category:'',year:new Date().getFullYear(),duration:'',poster:'',url:'',status:'Activo'};
const emptySeries={title:'',description:'',category:'',year:new Date().getFullYear(),poster:'',status:'Activo',seasons:1,episodes:1};

async function request(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'No se pudo completar la operación.');return data;}

function Form({type,initial,onCancel,onSaved}){const [form,setForm]=React.useState(initial|| (type==='vod'?emptyMovie:emptySeries));const [saving,setSaving]=React.useState(false);const [error,setError]=React.useState('');const set=(key,value)=>setForm(prev=>({...prev,[key]:value}));const save=async e=>{e.preventDefault();setSaving(true);setError('');try{const item=await request(`/api/${type==='vod'?'vod':'series'}${form.id?`/${form.id}`:''}`,{method:form.id?'PUT':'POST',body:JSON.stringify(form)});onSaved(item);}catch(err){setError(err.message);}finally{setSaving(false);}};return <div className="modal-backdrop"><form className="modal vod-modal" onSubmit={save}><div className="modal-head"><div><h2>{form.id?'Editar':'Nuevo'} {type==='vod'?'contenido VOD':'serie'}</h2><p>Los datos quedan preparados para backend persistente.</p></div><button type="button" className="icon-button" onClick={onCancel}><X size={18}/></button></div>{error&&<div className="vod-error">{error}</div>}<div className="form-grid"><label>Título<input value={form.title} onChange={e=>set('title',e.target.value)} required/></label><label>Categoría<input value={form.category} onChange={e=>set('category',e.target.value)} required/></label><label>Año<input type="number" min="1900" max="2100" value={form.year} onChange={e=>set('year',e.target.value)}/></label>{type==='vod'?<><label>Duración<input value={form.duration} onChange={e=>set('duration',e.target.value)} placeholder="01:45:00"/></label><label>URL / fuente<input value={form.url} onChange={e=>set('url',e.target.value)} placeholder="https://..."/></label></>:<><label>Temporadas<input type="number" min="1" value={form.seasons} onChange={e=>set('seasons',e.target.value)}/></label><label>Episodios<input type="number" min="1" value={form.episodes} onChange={e=>set('episodes',e.target.value)}/></label></>}<label>Poster<input value={form.poster} onChange={e=>set('poster',e.target.value)} placeholder="https://..."/></label><label>Estado<select value={form.status} onChange={e=>set('status',e.target.value)}><option>Activo</option><option>Inactivo</option></select></label><label className="full">Descripción<textarea value={form.description} onChange={e=>set('description',e.target.value)} rows="3"/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Guardando...':'Guardar'}</button></div></form></div>}

function Catalog({type}){const [items,setItems]=React.useState([]);const [query,setQuery]=React.useState('');const [loading,setLoading]=React.useState(true);const [error,setError]=React.useState('');const [form,setForm]=React.useState(null);const path=type==='vod'?'vod':'series';const load=React.useCallback(async()=>{setLoading(true);try{setItems(await request(`/api/${path}`));setError('');}catch(err){setError(err.message);}finally{setLoading(false);}},[path]);React.useEffect(()=>{load();},[load]);const filtered=items.filter(item=>[item.title,item.category,item.year,item.status].join(' ').toLowerCase().includes(query.toLowerCase()));const remove=async item=>{if(!window.confirm(`¿Eliminar ${item.title}?`))return;try{await request(`/api/${path}/${item.id}`,{method:'DELETE'});setItems(prev=>prev.filter(x=>x.id!==item.id));}catch(err){setError(err.message);}};return <div className="vod-section"><div className="module-head"><div className="module-title"><div className="module-icon">{type==='vod'?<Film size={22}/>:<Tv2 size={22}/>}</div><div><h2>{type==='vod'?'VOD':'Series'}</h2><p>{type==='vod'?'Películas y contenido bajo demanda.':'Series, temporadas y episodios preparados para crecer.'}</p></div></div><button className="primary-button" onClick={()=>setForm({type,initial:null})}><Plus size={16}/>Nuevo</button></div><div className="toolbar"><div className="module-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar ${type==='vod'?'película':'serie'}...`}/></div></div>{error&&<div className="vod-error">{error}</div>}<div className="card module-table"><div className="table-info"><span>{filtered.length} registros</span><span>Persistencia compartida por API</span></div><div className="table-scroll"><table><thead><tr><th>Título</th><th>Categoría</th><th>Año</th>{type==='vod'?<><th>Duración</th><th>Fuente</th></>:<><th>Temporadas</th><th>Episodios</th></>}<th>Estado</th><th>Acciones</th></tr></thead><tbody>{loading?<tr><td colSpan="7">Cargando...</td></tr>:filtered.map(item=><tr key={item.id}><td><strong>{item.title}</strong></td><td>{item.category}</td><td>{item.year}</td>{type==='vod'?<><td>{item.duration||'—'}</td><td>{item.url?'Configurada':'Sin fuente'}</td></>:<><td>{item.seasons}</td><td>{item.episodes}</td></>}<td><span className={`status-badge ${item.status==='Activo'?'success':'warning'}`}>{item.status}</span></td><td><div className="row-actions"><button className="icon-button" title="Editar" onClick={()=>setForm({type,initial:item})}><Edit3 size={15}/></button><button className="icon-button danger-icon" title="Eliminar" onClick={()=>remove(item)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></div>{form&&<Form type={form.type} initial={form.initial} onCancel={()=>setForm(null)} onSaved={item=>{setItems(prev=>form.initial?prev.map(x=>x.id===item.id?item:x):[item,...prev]);setForm(null);}}/>}</div>}

export default function Vod(){return <div className="vod-page"><div className="page-heading"><div><h1>VOD / Series</h1><p>Administra películas, series y catálogo bajo demanda.</p></div></div><div className="content-tabs"><Catalog type="vod"/><Catalog type="series"/></div></div>}
