import React from 'react';
import { Edit3, MoreVertical, Plus, Search, SlidersHorizontal, Trash2, X, Save } from 'lucide-react';
import { createPackage, deletePackage, getPackages, updatePackage } from './services/packagesApi.js';
import './styles/packages.css';

const empty={name:'',description:'',price:'',duration:30,maxConnections:1,status:'Activo'};

export default function Packages(){
  const [items,setItems]=React.useState([]); const [q,setQ]=React.useState(''); const [status,setStatus]=React.useState('Todos');
  const [editing,setEditing]=React.useState(null); const [form,setForm]=React.useState(empty); const [error,setError]=React.useState('');
  const load=React.useCallback(async()=>{try{setItems(await getPackages())}catch(e){setError(e.message)}},[]);
  React.useEffect(()=>{load()},[load]);
  const open=(item=null)=>{setEditing(item);setForm(item?{...item}:empty);setError('')};
  const save=async()=>{try{setError('');const payload={...form,price:Number(form.price),duration:Number(form.duration),maxConnections:Number(form.maxConnections)}; if(!payload.name.trim())throw new Error('El nombre del paquete es obligatorio.'); if(payload.price<0)throw new Error('El precio no puede ser negativo.'); if(payload.duration<1)throw new Error('La duración debe ser mayor a 0 días.'); if(payload.maxConnections<1||payload.maxConnections>99)throw new Error('Las conexiones deben estar entre 1 y 99.'); if(editing)await updatePackage(editing.id,payload);else await createPackage(payload); await load();setEditing(null)}catch(e){setError(e.message)}};
  const remove=async id=>{if(!window.confirm('¿Eliminar este paquete?'))return;try{await deletePackage(id);await load()}catch(e){setError(e.message)}};
  const filtered=items.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())&&(status==='Todos'||x.status===status));
  return <div className="module-page packages-page"><div className="module-head"><div className="module-title"><div className="module-icon"><Plus size={22}/></div><div><h1>Paquetes / Perfiles</h1><p>Define planes, límites y condiciones comerciales.</p></div></div><button className="primary-button" onClick={()=>open()}><Plus size={16}/>Nuevo paquete</button></div>
    <div className="package-summary"><div><span>Paquetes</span><strong>{items.length}</strong></div><div><span>Activos</span><strong>{items.filter(x=>x.status==='Activo').length}</strong></div><div><span>Conexión máxima</span><strong>{items.reduce((a,x)=>a+Number(x.maxConnections||0),0)}</strong></div></div>
    <div className="toolbar"><div className="module-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar paquete..."/></div><button className="filter-button" onClick={()=>setStatus(status==='Todos'?'Activo':'Todos')}><SlidersHorizontal size={13}/>Estado: {status}<span>⌄</span></button></div>
    {error&&<div className="module-error">{error}</div>}
    <div className="card module-table"><div className="table-info"><span>{filtered.length} registros</span><span>Persistencia mediante API</span></div><div className="table-scroll"><table><thead><tr><th>Paquete</th><th>Descripción</th><th>Precio</th><th>Duración</th><th>Conexiones</th><th>Usuarios</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.description||'—'}</td><td>$ {Number(x.price).toFixed(2)}</td><td>{x.duration} días</td><td>{x.maxConnections}</td><td>{x.userCount||0}</td><td><span className={`status-badge ${x.status==='Activo'?'success':'warning'}`}>{x.status}</span></td><td><button className="icon-button" onClick={()=>open(x)} title="Editar"><Edit3 size={15}/></button><button className="icon-button danger-icon" onClick={()=>remove(x.id)} title="Eliminar"><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div>
    {editing!==null&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{editing.id?'Editar paquete':'Nuevo paquete'}</h2><p>Configura los límites comerciales.</p></div><button className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="form-grid"><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Precio<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Duración (días)<input type="number" min="1" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><label>Máx. conexiones<input type="number" min="1" max="99" value={form.maxConnections} onChange={e=>setForm({...form,maxConnections:e.target.value})}/></label><label className="full">Descripción<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Activo</option><option>Inactivo</option></select></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary-button" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary-button" onClick={save}><Save size={15}/>Guardar</button></div></div></div>}
  </div>
}
