import React from 'react';
import { Save,X,Radio,Hash,Folder,CircleCheck,Image as ImageIcon,Link2,Activity,Settings2,Info,Clock3,ExternalLink } from 'lucide-react';
import SourceEditor from './SourceEditor.jsx';

const empty={number:'',name:'',category:'',status:'Activo',logo:'',sources:[]};
const tabs=[['general','Información general',Radio],['sources','Fuentes de transmisión',Link2],['monitor','Estado y monitoreo',Activity],['advanced','Opciones avanzadas',Settings2]];
function uptime(startedAt){if(!startedAt)return'—';const s=Math.max(0,Math.floor((Date.now()-new Date(startedAt).getTime())/1000)),d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60);return d?`${d}d ${h}h ${m}m`:h?`${h}h ${m}m`:`${m}m ${s%60}s`;}

export default function ChannelForm({initial,categories,saving,externalError,onSave,onCancel,stream}){
 const [form,setForm]=React.useState({...empty,...initial,sources:(initial?.sources||[]).map(source=>({...source}))});const [error,setError]=React.useState('');const [tab,setTab]=React.useState('general');const [,tick]=React.useState(0);const set=(key,value)=>setForm(prev=>({...prev,[key]:value}));
 React.useEffect(()=>{if(stream?.status!=='running')return;const t=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(t);},[stream?.status]);
 const submit=async e=>{e.preventDefault();setError('');const number=Number(form.number);if(!Number.isInteger(number)||number<1||number>99999){setTab('general');return setError('El número de canal debe ser un entero entre 1 y 99999.');}if(!form.name.trim()){setTab('general');return setError('El nombre del canal es obligatorio.');}if(!form.category.trim()){setTab('general');return setError('La categoría es obligatoria.');}if(!form.sources.length){setTab('sources');return setError('Agrega al menos una fuente.');}if(form.sources.some(s=>!s.url.trim())){setTab('sources');return setError('Todas las fuentes deben tener una URL.');}const priorities=form.sources.map(s=>Number(s.priority));if(priorities.some(v=>!Number.isInteger(v)||v<1||v>99)){setTab('sources');return setError('La prioridad de cada fuente debe estar entre 1 y 99.');}const ok=await onSave({...form,number,name:form.name.trim(),category:form.category.trim(),logo:form.logo.trim(),sources:form.sources.map(s=>({...s,url:s.url.trim()}))});if(!ok)setError('No se pudo guardar. Revisa los datos del formulario.');};
 const running=stream?.status==='running';
 return <div className="modal-backdrop"><form className="modal channel-modal channel-modal-tabs" onSubmit={submit}>
  <div className="channel-modal-head"><div className="channel-modal-title"><div className="channel-title-icon"><Radio size={22}/></div><div><h2>{initial?'Editar canal':'Agregar canal'}</h2><p>Define la información del canal y sus fuentes de transmisión.</p></div></div><button type="button" className="icon-button" onClick={onCancel} disabled={saving}><X size={20}/></button></div>
  <nav className="channel-tabs">{tabs.map(([id,label,Icon])=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/><span>{label}</span></button>)}</nav>
  {(error||externalError)&&<div className="form-error channel-form-error" role="alert">{error||externalError}</div>}
  <div className="channel-tab-body">
   {tab==='general'&&<div className="general-layout"><section className="wide-card"><div className="wide-section-head"><div className="wide-icon"><Info size={21}/></div><div><h3>Información general</h3><p>Datos básicos del canal, categoría y apariencia.</p></div></div><label className="channel-field channel-name-field">Nombre del canal <b>*</b><div className="input-with-icon"><Radio size={16}/><input autoFocus value={form.name} onChange={e=>set('name',e.target.value)} placeholder="ESPN 2" disabled={saving}/></div></label><div className="general-fields"><label className="channel-field">Número<div className="input-with-icon"><Hash size={16}/><input type="number" min="1" max="99999" value={form.number} onChange={e=>set('number',e.target.value)} disabled={saving}/></div></label><label className="channel-field">Categoría<div className="input-with-icon"><Folder size={16}/><input list="channel-categories" value={form.category} onChange={e=>set('category',e.target.value)} placeholder="Deportes" disabled={saving}/></div><datalist id="channel-categories">{categories.map(x=><option key={x} value={x}/>)}</datalist></label><label className="channel-field">Estado<div className="input-with-icon"><CircleCheck size={16}/><select value={form.status} onChange={e=>set('status',e.target.value)} disabled={saving}><option>Activo</option><option>Inactivo</option></select></div></label></div></section><section className="wide-card logo-wide-card"><div className="wide-section-head"><div className="wide-icon"><ImageIcon size={21}/></div><div><h3>Logo del canal</h3><p>URL de imagen y vista previa.</p></div></div><label className="channel-field">URL del logo<input value={form.logo} onChange={e=>set('logo',e.target.value)} placeholder="https://servidor/logo.png" disabled={saving}/></label><div className="logo-wide-preview">{form.logo?<img src={form.logo} alt="Vista previa"/>:<><ImageIcon size={38}/><span>Sin logo</span></>}</div></section></div>}
   {tab==='sources'&&<section className="wide-card sources-wide-card"><SourceEditor sources={form.sources} onChange={sources=>set('sources',sources)} disabled={saving}/></section>}
   {tab==='monitor'&&<div className="monitor-layout"><section className="wide-card monitor-status"><div className="wide-section-head"><div className="wide-icon"><Activity size={21}/></div><div><h3>Estado de la emisión</h3><p>Información entregada por el proceso real FFmpeg/HLS.</p></div></div><div className={`monitor-state ${running?'live':stream?.status==='error'?'error':'off'}`}><span></span><div><strong>{running?'Funcionando':stream?.status==='starting'?'Iniciando':stream?.status==='error'?'Error':'Detenido'}</strong><small>{running?'El canal está procesando señal.':'No hay una emisión activa en este momento.'}</small></div></div><div className="monitor-metrics"><div><Clock3 size={18}/><span>Tiempo activo</span><strong>{running?uptime(stream?.startedAt):'—'}</strong></div><div><Link2 size={18}/><span>Salida HLS</span><strong>{stream?.hlsUrl?'Disponible':'No disponible'}</strong></div></div>{stream?.hlsUrl&&<a className="monitor-link" href={stream.hlsUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Abrir salida HLS</a>}{stream?.lastError&&<div className="monitor-error">{stream.lastError}</div>}</section><section className="wide-card"><div className="wide-section-head"><div className="wide-icon"><Link2 size={21}/></div><div><h3>Fuentes configuradas</h3><p>Resumen de las entradas del canal.</p></div></div><div className="source-monitor-list">{form.sources.map((s,i)=><div key={s.id||i}><b>{i+1}</b><span>{s.originType==='ASTRA'?'Astra Cesbo':s.originType==='M3U'?'M3U / M3U8':'HTTP / URL directa'}</span><code>{s.url||'Sin URL'}</code><em>P{s.priority}</em></div>)}</div></section></div>}
   {tab==='advanced'&&<section className="wide-card advanced-placeholder"><Settings2 size={36}/><h3>Opciones avanzadas</h3><p>Esta sección queda preparada para parámetros avanzados del motor. No se muestran controles ficticios hasta que esas funciones estén implementadas en el backend.</p></section>}
  </div>
  <div className="channel-modal-footer"><div className="channel-help"><strong>¿Necesitas ayuda?</strong><span>HTTP/HLS directo · Astra Cesbo por HTTP · M3U/M3U8 para importación.</span></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onCancel} disabled={saving}>Cancelar</button><button type="submit" className="primary-button" disabled={saving}><Save size={15}/>{saving?'Guardando...':'Guardar canal'}</button></div></div>
 </form></div>;
}
