import React from 'react';
import { Plus,Trash2,Link2,Info,Server,ListVideo,Play,PenLine,LoaderCircle,CheckCircle2,XCircle,Gauge,Monitor,Video,Volume2,AudioLines,RefreshCw } from 'lucide-react';
import { probeChannelSource } from '../services/channelsApi.js';
const blank=(priority=1)=>({id:`source-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,url:'',originType:'HTTP',protocol:'HLS',status:'Activa',priority});
const codec=value=>value?String(value).toUpperCase().replace('H264','H.264').replace('HEVC','H.265'):'—';
const mediaItems=media=>[
 {icon:Gauge,label:'Bitrate',value:media?.bitrateKbps?`${media.bitrateKbps.toLocaleString()} Kbps`:'—'},
 {icon:Monitor,label:'Resolución',value:media?.width&&media?.height?`${media.width} × ${media.height}`:'—'},
 {icon:Video,label:'Video',value:codec(media?.videoCodec)},
 {icon:Volume2,label:'Audio',value:codec(media?.audioCodec)},
 {icon:AudioLines,label:'Canales',value:media?.audioChannels?`${media.audioChannels}x${media.audioLayout?` · ${media.audioLayout}`:''}`:'—'},
 {icon:RefreshCw,label:'FPS',value:media?.fps?`${media.fps} FPS`:'—'}
];
export default function SourceEditor({sources,onChange,disabled}){
 const[tests,setTests]=React.useState({});const add=()=>onChange([...sources,blank(sources.length+1)]);const update=(index,key,value)=>{onChange(sources.map((s,i)=>i===index?{...s,[key]:key==='priority'?Number(value):value}:s));setTests(t=>({...t,[index]:null}));};const remove=index=>{onChange(sources.filter((_,i)=>i!==index));setTests({});};
 const probe=async(index)=>{const source=sources[index];if(!source?.url?.trim())return setTests(t=>({...t,[index]:{loading:false,ok:false,status:'error',label:'Error',message:'Ingresa primero la URL.',responseMs:null}}));setTests(t=>({...t,[index]:{loading:true}}));try{const result=await probeChannelSource(source);setTests(t=>({...t,[index]:{...result,loading:false}}));}catch(e){setTests(t=>({...t,[index]:{loading:false,ok:false,status:'error',label:'Error',message:e.message||'No se pudo probar la fuente.',responseMs:null}}));}};
 return <div className="source-editor-v2"><div className="source-head-v2"><div className="channel-section-title source-section-title"><span>2</span><div><h3>Fuentes de transmisión</h3><p>Añade una o más fuentes para este canal. Puedes probarlas antes de guardar.</p></div></div><button type="button" className="primary-button compact" onClick={add} disabled={disabled}><Plus size={15}/>Agregar fuente</button></div><div className="source-tip"><Info size={17}/><span>La fuente con prioridad <strong>1</strong> será la principal. Usa <strong>Probar</strong> para comprobar señal, tiempo de respuesta y características multimedia sin guardar el canal.</span></div>
 {sources.length===0&&<div className="source-empty-v2"><Link2 size={25}/><strong>Sin fuentes</strong><span>Agrega una URL HTTP/HLS o un stream HTTP publicado por Astra Cesbo.</span><button type="button" className="secondary-button" onClick={add} disabled={disabled}><Plus size={14}/>Agregar primera fuente</button></div>}
 <div className="source-card-list">{sources.map((source,index)=>{const test=tests[index];return <div className="source-card" key={source.id||index}><div className="source-card-head"><div className="source-card-number">{index+1}</div><span className={`source-role ${Number(source.priority)===1?'primary':'backup'}`}>{Number(source.priority)===1?'Principal':'Respaldo'}</span><div className={`source-test-state ${test?.loading?'testing':test?.ok?'ok':test?'bad':'idle'}`}>{test?.loading?<><LoaderCircle size={14} className="spin"/>Probando</>:test?.ok?<><CheckCircle2 size={14}/>Activa</>:test?<><XCircle size={14}/>{test.label||'Error'}</>:<><span className="dot-off"/>Sin comprobar</>}</div><div className="source-card-actions"><button type="button" className="source-test-button" onClick={()=>probe(index)} disabled={disabled||test?.loading}><Play size={14}/>Probar</button><button type="button" className="source-edit-button" onClick={()=>document.getElementById(`source-url-${index}`)?.focus()} disabled={disabled}><PenLine size={14}/>Editar</button><button type="button" className="source-delete" onClick={()=>remove(index)} disabled={disabled}><Trash2 size={14}/>Eliminar</button></div></div>
 <div className="source-card-grid"><label className="channel-field">Tipo de fuente<div className="input-with-icon">{source.originType==='ASTRA'?<Server size={16}/>:source.originType==='M3U'?<ListVideo size={16}/>:<Link2 size={16}/>}<select disabled={disabled} value={source.originType||'HTTP'} onChange={e=>update(index,'originType',e.target.value)}><option value="HTTP">HTTP / URL directa</option><option value="ASTRA">Astra Cesbo</option><option value="M3U">M3U / M3U8</option></select></div></label><label className="channel-field source-url-field">URL del stream <b>*</b><div className="input-with-icon"><Link2 size={16}/><input id={`source-url-${index}`} disabled={disabled} value={source.url} onChange={e=>update(index,'url',e.target.value)} placeholder={source.originType==='ASTRA'?'http://IP_ASTRA:8000/canal':source.originType==='M3U'?'https://servidor/lista.m3u8':'https://servidor/stream.m3u8'}/></div></label><label className="channel-field">Protocolo<select disabled={disabled} value={source.protocol||'HLS'} onChange={e=>update(index,'protocol',e.target.value)}><option>HLS</option><option>HTTP</option><option>HTTPS</option><option>MPEG-TS</option><option>RTMP</option><option>RTSP</option><option>Otro</option></select></label><label className="channel-field">Prioridad<input disabled={disabled} type="number" min="1" max="99" value={source.priority} onChange={e=>update(index,'priority',e.target.value)}/></label><div className="channel-field source-response"><span>Tiempo de respuesta</span><strong className={test?.ok?'ok':test?'bad':''}>{test?.loading?'Comprobando…':test?.responseMs!=null?`${test.ok?'Ok':'Respuesta'} (${test.responseMs} ms)`:'Sin comprobar'}</strong></div></div>
 {test?.ok&&<div className="source-media-strip">{mediaItems(test.media).map(({icon:Icon,label,value})=><div className="source-media-item" key={label}><Icon size={17}/><div><strong>{value}</strong><span>{label}</span></div></div>)}</div>}
 {test&&!test.loading&&<div className={`source-test-message ${test.ok?'ok':'bad'}`}>{test.message}</div>}</div>})}</div>
 <div className="source-examples"><strong><Link2 size={15}/> Ejemplos de URL</strong><span><b>HLS:</b> https://servidor/canal.m3u8</span><span><b>HTTP:</b> http://servidor/canal.ts</span><span><b>Astra:</b> http://IP_ASTRA:8000/canal</span></div></div>;
}
