import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR=path.resolve(__dirname,'../data');
const PORT=Number(process.env.IPZTREAM_API_PORT||3100);
const HOST=process.env.IPZTREAM_API_HOST||'127.0.0.1';
const files={nodes:path.join(DATA_DIR,'nodes.json'),channels:path.join(DATA_DIR,'channels.json'),vod:path.join(DATA_DIR,'vod.json'),series:path.join(DATA_DIR,'series.json'),epg:path.join(DATA_DIR,'epg.json'),m3u:path.join(DATA_DIR,'m3u.json'),packages:path.join(DATA_DIR,'packages.json'),connections:path.join(DATA_DIR,'connections.json'),devices:path.join(DATA_DIR,'devices.json')};
const seedNodes=[{id:'node-01',name:'Nodo 01 - Lima',status:'En línea',ip:'192.168.10.21',region:'Lima',cpu:22,ram:41,capacity:'10 Gbps'},{id:'node-02',name:'Nodo 02 - Arequipa',status:'En línea',ip:'192.168.10.22',region:'Arequipa',cpu:18,ram:36,capacity:'10 Gbps'},{id:'node-03',name:'Nodo 03 - Trujillo',status:'En línea',ip:'192.168.10.23',region:'Trujillo',cpu:27,ram:48,capacity:'5 Gbps'},{id:'node-05',name:'Nodo 05 - Piura',status:'Fuera de línea',ip:'192.168.10.25',region:'Piura',cpu:null,ram:null,capacity:'5 Gbps'}];
const seedChannels=[{id:'channel-espn',number:1,name:'ESPN',category:'Deportes',status:'Activo',logo:'',sources:[{id:'src-espn-1',url:'https://example.com/espn.m3u8',protocol:'HLS',status:'Activa',priority:1}]},{id:'channel-hbo',number:2,name:'HBO Max',category:'Entretenimiento',status:'Activo',logo:'',sources:[{id:'src-hbo-1',url:'https://example.com/hbo.m3u8',protocol:'HLS',status:'Activa',priority:1}]},{id:'channel-tudn',number:3,name:'TUDN',category:'Deportes',status:'Activo',logo:'',sources:[{id:'src-tudn-1',url:'https://example.com/tudn.m3u8',protocol:'HLS',status:'Activa',priority:1}]}];
const seedVod=[{id:'vod-demo-1',title:'Película de prueba',description:'Contenido demostrativo',category:'Películas',year:2026,duration:'01:45:00',poster:'',url:'',status:'Activo'}];
const seedSeries=[{id:'series-demo-1',title:'La Serie IPZ',description:'Serie demostrativa',category:'Series',year:2026,poster:'',status:'Activo',seasons:1,episodes:8}];
const seedEpg=[{id:'epg-1',channel:'ESPN',title:'Fútbol Internacional',start:'2026-09-13T18:00',end:'2026-09-13T20:00',description:'Programación de prueba',status:'Programado'},{id:'epg-2',channel:'HBO Max',title:'Película Prime',start:'2026-09-13T20:00',end:'2026-09-13T22:00',description:'Programación de prueba',status:'Programado'}];
const seedM3u=[{id:'m3u-premium',name:'Lista Premium',profile:'Premium',status:'Activo',description:'Lista demostrativa',sourceUrl:'',items:1024},{id:'m3u-basic',name:'Lista Básica',profile:'Básico',status:'Activo',description:'Lista demostrativa',sourceUrl:'',items:512}];
const seedPackages=[{id:'pkg-basic',name:'Básico',description:'Plan inicial',price:10,duration:30,maxConnections:1,status:'Activo',userCount:2},{id:'pkg-premium',name:'Premium',description:'Plan para usuarios avanzados',price:20,duration:30,maxConnections:3,status:'Activo',userCount:1},{id:'pkg-family',name:'Familia',description:'Plan multidispositivo',price:35,duration:30,maxConnections:5,status:'Activo',userCount:1}];
const seedConnections=[{id:'conn-01',username:'cliente01',device:'Smart TV Samsung',ip:'192.168.1.45',content:'ESPN',node:'Nodo 01',startedAt:'14:12',lastActivity:'14:28',status:'Activo'},{id:'conn-02',username:'cliente02',device:'Android TV',ip:'192.168.1.78',content:'HBO Max',node:'Nodo 02',startedAt:'14:10',lastActivity:'14:26',status:'Activo'},{id:'conn-03',username:'cliente03',device:'Fire TV',ip:'192.168.1.92',content:'Discovery',node:'Nodo 03',startedAt:'14:08',lastActivity:'14:24',status:'Activo'}];
const seedDevices=[{id:'dev-01',name:'Smart TV Samsung',identifier:'device-samsung-01',username:'cliente01',type:'TV',ip:'192.168.1.45',node:'Nodo 01',status:'Activo',lastActivity:'14:28'},{id:'dev-02',name:'Android TV Box',identifier:'device-android-01',username:'cliente02',type:'TV Box',ip:'192.168.1.78',node:'Nodo 02',status:'Activo',lastActivity:'14:26'},{id:'dev-03',name:'Fire TV',identifier:'device-fire-01',username:'cliente03',type:'TV Box',ip:'192.168.1.92',node:'Nodo 03',status:'Activo',lastActivity:'14:24'}];
const stores={vod:seedVod,series:seedSeries,epg:seedEpg,m3u:seedM3u,packages:seedPackages,connections:seedConnections,devices:seedDevices};
let writeQueue=Promise.resolve();
async function ensureStore(file,seed){await fs.mkdir(DATA_DIR,{recursive:true});try{await fs.access(file);}catch{await fs.writeFile(file,JSON.stringify(seed,null,2));}}
async function readStore(file,seed){await ensureStore(file,seed);return JSON.parse(await fs.readFile(file,'utf8'));}
function writeStore(file,data){writeQueue=writeQueue.then(async()=>{await fs.mkdir(DATA_DIR,{recursive:true});await fs.writeFile(file,JSON.stringify(data,null,2));});return writeQueue;}
function send(res,status,payload,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(payload));}
async function readBody(req){let body='';for await(const chunk of req)body+=chunk;if(body.length>1024*64)throw new Error('Solicitud demasiado grande.');return body?JSON.parse(body):{};}
function id(prefix){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;}
function validIPv4(ip){const parts=ip.split('.');return parts.length===4&&parts.every(part=>/^\d{1,3}$/.test(part)&&Number(part)>=0&&Number(part)<=255);}
function normalizeNode(input,current={}){return {id:current.id||id('node'),name:String(input.name??current.name??'').trim(),status:input.status==='Fuera de línea'?'Fuera de línea':'En línea',ip:String(input.ip??current.ip??'').trim(),region:String(input.region??current.region??'').trim(),cpu:input.cpu===null||input.cpu===''?null:Number(input.cpu),ram:input.ram===null||input.ram===''?null:Number(input.ram),capacity:String(input.capacity??current.capacity??'').trim()};}
function normalizeSource(input,index=0){return {id:String(input.id||id(`source-${index}`)),url:String(input.url||'').trim(),protocol:String(input.protocol||'HLS').trim(),status:input.status==='Inactiva'?'Inactiva':'Activa',priority:Number(input.priority||index+1)};}
function normalizeChannel(input,current={}){return {id:current.id||id('channel'),number:Number(input.number??current.number),name:String(input.name??current.name??'').trim(),category:String(input.category??current.category??'').trim(),status:input.status==='Inactivo'?'Inactivo':'Activo',logo:String(input.logo??current.logo??'').trim(),sources:Array.isArray(input.sources)?input.sources.map(normalizeSource):Array.isArray(current.sources)?current.sources.map(normalizeSource):[]};}
function validateChannel(channel,channels,idValue=null){if(!Number.isInteger(channel.number)||channel.number<1||channel.number>99999)return 'El número de canal debe ser un entero entre 1 y 99999.';if(!channel.name||!channel.category)return 'Nombre y categoría son obligatorios.';if(!channel.sources.length)return 'El canal debe tener al menos una fuente.';if(channel.sources.some(source=>!source.url))return 'Todas las fuentes deben tener una URL.';if(channel.sources.some(source=>!Number.isInteger(source.priority)||source.priority<1||source.priority>99))return 'La prioridad de cada fuente debe estar entre 1 y 99.';if(channels.some(item=>item.number===channel.number&&item.id!==idValue))return `El número ${channel.number} ya está asignado a otro canal.`;return null;}
function normalizeGeneric(type,input,current={}){const value={...current,...input,id:current.id||input.id||id(type)};if(type==='vod')return {id:value.id,title:String(value.title||'').trim(),description:String(value.description||'').trim(),category:String(value.category||'').trim(),year:Number(value.year)||new Date().getFullYear(),duration:String(value.duration||'').trim(),poster:String(value.poster||'').trim(),url:String(value.url||'').trim(),status:value.status==='Inactivo'?'Inactivo':'Activo'};if(type==='series')return {id:value.id,title:String(value.title||'').trim(),description:String(value.description||'').trim(),category:String(value.category||'').trim(),year:Number(value.year)||new Date().getFullYear(),poster:String(value.poster||'').trim(),status:value.status==='Inactivo'?'Inactivo':'Activo',seasons:Math.max(1,Number(value.seasons)||1),episodes:Math.max(1,Number(value.episodes)||1)};if(type==='epg')return {id:value.id,channel:String(value.channel||'').trim(),title:String(value.title||'').trim(),start:String(value.start||''),end:String(value.end||''),description:String(value.description||'').trim(),status:['Programado','Emitido','Cancelado'].includes(value.status)?value.status:'Programado'};if(type==='m3u')return {id:value.id,name:String(value.name||'').trim(),profile:String(value.profile||'').trim(),status:value.status==='Inactivo'?'Inactivo':'Activo',description:String(value.description||'').trim(),sourceUrl:String(value.sourceUrl||'').trim(),items:Math.max(0,Number(value.items)||0)};if(type==='packages')return {id:value.id,name:String(value.name||'').trim(),description:String(value.description||'').trim(),price:Number(value.price)||0,duration:Math.max(1,Number(value.duration)||30),maxConnections:Math.max(1,Number(value.maxConnections)||1),status:value.status==='Inactivo'?'Inactivo':'Activo',userCount:Math.max(0,Number(value.userCount)||0)};return value;}
function validateGeneric(type,item,list,idValue=null){if(type==='vod'||type==='series')return item.title&&item.category?null:'Título y categoría son obligatorios.';if(type==='epg'){if(!item.channel||!item.title||!item.start||!item.end)return 'Canal, título, inicio y fin son obligatorios.';if(new Date(item.end)<=new Date(item.start))return 'La hora de fin debe ser posterior al inicio.';return null;}if(type==='m3u')return item.name?'':'El nombre de la lista es obligatorio.';if(type==='packages'){if(!item.name)return 'El nombre del paquete es obligatorio.';if(item.price<0)return 'El precio no puede ser negativo.';if(item.duration<1)return 'La duración debe ser mayor a 0 días.';if(item.maxConnections<1||item.maxConnections>99)return 'Las conexiones deben estar entre 1 y 99.';if(list.some(x=>x.name.toLowerCase()===item.name.toLowerCase()&&x.id!==idValue))return `El paquete ${item.name} ya existe.`;return null;}return null;}
async function handler(req,res){try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true});
if(url.pathname==='/api/nodes'&&req.method==='GET')return send(res,200,{nodes:await readStore(files.nodes,seedNodes)});
if(url.pathname==='/api/nodes'&&req.method==='POST'){const input=normalizeNode(await readBody(req));if(!input.name||!input.ip||!input.region||!input.capacity)return send(res,400,{message:'Nombre, IP, región y capacidad son obligatorios.'});if(!validIPv4(input.ip))return send(res,400,{message:'Ingresa una dirección IPv4 válida.'});if((input.cpu!==null&&(Number.isNaN(input.cpu)||input.cpu<0||input.cpu>100))||(input.ram!==null&&(Number.isNaN(input.ram)||input.ram<0||input.ram>100)))return send(res,400,{message:'CPU y RAM deben estar entre 0 y 100.'});const nodes=await readStore(files.nodes,seedNodes);if(nodes.some(node=>node.ip.toLowerCase()===input.ip.toLowerCase()))return send(res,409,{message:`La IP ${input.ip} ya está registrada en otro nodo.`});nodes.unshift(input);await writeStore(files.nodes,nodes);return send(res,201,input);}
const nodeMatch=url.pathname.match(/^\/api\/nodes\/([^/]+)$/);if(nodeMatch&&req.method==='DELETE'){const idValue=decodeURIComponent(nodeMatch[1]);const nodes=await readStore(files.nodes,seedNodes);const next=nodes.filter(node=>node.id!==idValue);if(next.length===nodes.length)return send(res,404,{message:'Nodo no encontrado.'});await writeStore(files.nodes,next);return send(res,200,{ok:true});}
if(url.pathname==='/api/channels'&&req.method==='GET')return send(res,200,{channels:await readStore(files.channels,seedChannels)});
if(url.pathname==='/api/channels'&&req.method==='POST'){const channels=await readStore(files.channels,seedChannels);const channel=normalizeChannel(await readBody(req));const validation=validateChannel(channel,channels);if(validation)return send(res,400,{message:validation});channels.unshift(channel);await writeStore(files.channels,channels);return send(res,201,channel);}
const channelMatch=url.pathname.match(/^\/api\/channels\/([^/]+)$/);if(channelMatch){const idValue=decodeURIComponent(channelMatch[1]);const channels=await readStore(files.channels,seedChannels);const index=channels.findIndex(channel=>channel.id===idValue);if(index<0)return send(res,404,{message:'Canal no encontrado.'});if(req.method==='PUT'){const channel=normalizeChannel(await readBody(req),channels[index]);const validation=validateChannel(channel,channels,idValue);if(validation)return send(res,400,{message:validation});channels[index]=channel;await writeStore(files.channels,channels);return send(res,200,channel);}if(req.method==='DELETE'){channels.splice(index,1);await writeStore(files.channels,channels);return send(res,200,{ok:true});}}
if(url.pathname==='/api/packages'&&req.method==='GET')return send(res,200,{packages:await readStore(files.packages,seedPackages)});
if(url.pathname==='/api/packages'&&req.method==='POST'){const list=await readStore(files.packages,seedPackages);const item=normalizeGeneric('packages',await readBody(req));const validation=validateGeneric('packages',item,list);if(validation)return send(res,409,{message:validation});list.unshift(item);await writeStore(files.packages,list);return send(res,201,item);}
const packageMatch=url.pathname.match(/^\/api\/packages\/([^/]+)$/);if(packageMatch){const idValue=decodeURIComponent(packageMatch[1]);const list=await readStore(files.packages,seedPackages);const index=list.findIndex(x=>x.id===idValue);if(index<0)return send(res,404,{message:'Paquete no encontrado.'});if(req.method==='PUT'){const item=normalizeGeneric('packages',await readBody(req),list[index]);const validation=validateGeneric('packages',item,list,idValue);if(validation)return send(res,409,{message:validation});list[index]=item;await writeStore(files.packages,list);return send(res,200,item)}if(req.method==='DELETE'){list.splice(index,1);await writeStore(files.packages,list);return send(res,200,{ok:true})}}
if(url.pathname==='/api/connections'&&req.method==='GET')return send(res,200,{connections:await readStore(files.connections,seedConnections)});
const connectionClose=url.pathname.match(/^\/api\/connections\/([^/]+)\/close$/);if(connectionClose&&req.method==='POST'){const idValue=decodeURIComponent(connectionClose[1]);const list=await readStore(files.connections,seedConnections);const item=list.find(x=>x.id===idValue);if(!item)return send(res,404,{message:'Conexión no encontrada.'});item.status='Cerrada';item.lastActivity=new Date().toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'});await writeStore(files.connections,list);return send(res,200,item)}
if(url.pathname==='/api/devices'&&req.method==='GET')return send(res,200,{devices:await readStore(files.devices,seedDevices)});
const deviceUnlink=url.pathname.match(/^\/api\/devices\/([^/]+)\/unlink$/);if(deviceUnlink&&req.method==='POST'){const idValue=decodeURIComponent(deviceUnlink[1]);const list=await readStore(files.devices,seedDevices);const item=list.find(x=>x.id===idValue);if(!item)return send(res,404,{message:'Dispositivo no encontrado.'});item.username='';item.status='Sin asociar';await writeStore(files.devices,list);return send(res,200,item)}
for(const type of ['vod','series','epg','m3u']){const collection=`/api/${type}`;if(url.pathname===collection&&req.method==='GET')return send(res,200,await readStore(files[type],stores[type]));if(url.pathname===collection&&req.method==='POST'){const list=await readStore(files[type],stores[type]);const item=normalizeGeneric(type,await readBody(req));const validation=validateGeneric(type,item);if(validation)return send(res,400,{message:validation});list.unshift(item);await writeStore(files[type],list);return send(res,201,item);}const match=url.pathname.match(new RegExp(`^/api/${type}/([^/]+)$`));if(match){const idValue=decodeURIComponent(match[1]);const list=await readStore(files[type],stores[type]);const index=list.findIndex(item=>item.id===idValue);if(index<0)return send(res,404,{message:'Registro no encontrado.'});if(req.method==='PUT'){const item=normalizeGeneric(type,await readBody(req),list[index]);const validation=validateGeneric(type,item);if(validation)return send(res,400,{message:validation});list[index]=item;await writeStore(files[type],list);return send(res,200,item);}if(req.method==='DELETE'){list.splice(index,1);await writeStore(files[type],list);return send(res,200,{ok:true});}}}
return send(res,404,{message:'Ruta no encontrada.'});}catch(error){console.error(error);return send(res,500,{message:error.message||'Error interno del servidor.'});}}
for(const [type,seed] of Object.entries(stores))await ensureStore(files[type],seed);await ensureStore(files.nodes,seedNodes);await ensureStore(files.channels,seedChannels);http.createServer(handler).listen(PORT,HOST,()=>console.log(`IPZStream API escuchando en http://${HOST}:${PORT}`));
