// IPZStream secure entry — authenticated API gateway.
import http from 'node:http';
import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import path from 'node:path';
import { URL } from 'node:url';
import { ensureAuthSchema, authenticate, getSessionUser, destroySession, serializeSessionCookie, clearSessionCookie, hasPermission, permissionForRequest } from './auth.js';
import { addAudit } from './db.js';
import { ensureUserSchema, listUsers, createUser, updateUser, deleteUser } from './user-service.js';
import { ensureClientSessionSchema, authenticateClient, createClientSession, getClientSession, destroyClientSession, clientSessionCookie, clearClientSessionCookie, getClientToken, publicClient } from './client-auth.js';
import { assertFfmpeg, getStream, listStreams, startStream, stopStream, restartStream, clearStreamHistory } from './stream-manager.js';
import { getUpdateStatus, installUpdate } from './update-service.js';
import { probeSource } from './source-probe.js';
const PUBLIC_PORT=Number(process.env.IPZTREAM_API_PORT||3100),INTERNAL_PORT=Number(process.env.IPZTREAM_INTERNAL_API_PORT||3101),HOST=process.env.IPZTREAM_API_HOST||'127.0.0.1',STREAM_ROOT=path.resolve(process.env.IPZTREAM_STREAM_ROOT||'/var/lib/ipztream/streams');function send(res,status,payload,extraHeaders={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':process.env.IPZTREAM_CORS_ORIGIN||'*','Access-Control-Allow-Credentials':'true',...extraHeaders});res.end(JSON.stringify(payload))}async function readBody(req){let body='';for await(const chunk of req)body+=chunk;if(body.length>64*1024)throw new Error('Solicitud demasiado grande.');return body?JSON.parse(body):{}}function clientIp(req){return String(req.headers['x-forwarded-for']||req.headers['x-real-ip']||req.socket.remoteAddress||'').split(',')[0].trim()}function sessionToken(req){return decodeURIComponent((req.headers.cookie||'').match(/(?:^|;\s*)ipztream_session=([^;]+)/)?.[1]||'')}function safeStreamPath(channelId,filename){if(!/^[A-Za-z0-9_-]{1,191}$/.test(channelId))return null;if(filename!=='index.m3u8'&&!/^segment_[0-9]{6}\.ts$/.test(filename))return null;const root=path.resolve(STREAM_ROOT),outputDir=path.resolve(root,channelId),filePath=path.resolve(outputDir,filename);return filePath.startsWith(`${outputDir}${path.sep}`)?filePath:null}async function handleHls(req,res,pathname){if(!['GET','HEAD'].includes(req.method))return false;const m=pathname.match(/^\/streams\/([^/]+)\/(index\.m3u8|segment_[0-9]{6}\.ts)$/);if(!m)return false;const channelId=decodeURIComponent(m[1]),filename=m[2],filePath=safeStreamPath(channelId,filename);if(!filePath)return send(res,400,{message:'Ruta HLS no válida.'});if(!['starting','running'].includes(getStream(channelId)?.status))return send(res,404,{message:'Stream no disponible.'});try{const info=await stat(filePath),headers={'Content-Type':filename==='index.m3u8'?'application/vnd.apple.mpegurl':'video/mp2t','Content-Length':String(info.size),'Cache-Control':filename==='index.m3u8'?'no-cache, no-store, must-revalidate':'public, max-age=10'};res.writeHead(200,headers);return req.method==='HEAD'?res.end():createReadStream(filePath).pipe(res)}catch{return send(res,404,{message:'Archivo HLS no encontrado.'})}}function proxyRequest(req,res,body){const options={hostname:HOST,port:INTERNAL_PORT,path:req.url,method:req.method,headers:{...req.headers,host:`${HOST}:${INTERNAL_PORT}`,'x-real-ip':clientIp(req)}};delete options.headers['content-length'];const proxy=http.request(options,u=>{res.writeHead(u.statusCode||502,{...u.headers,'cache-control':'no-store'});u.pipe(res)});proxy.on('error',e=>send(res,502,{message:`API interna no disponible: ${e.message}`}));if(body?.length)proxy.write(body);proxy.end()}
async function handleUserApi(req,res,user){const pathname=new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname,m=pathname.match(/^\/api\/users(?:\/([^/]+))?$/);if(!m)return false;const id=m[1]?decodeURIComponent(m[1]):null,actor=user.username;try{if(req.method==='GET'&&!id)return send(res,200,{users:await listUsers()});if(req.method==='POST'&&!id)return send(res,201,await createUser(await readBody(req),actor));if(req.method==='PUT'&&id){const x=await updateUser(id,await readBody(req),actor);return send(res,x?200:404,x||{message:'Usuario no encontrado.'})}if(req.method==='DELETE'&&id)return send(res,(await deleteUser(id,actor))?200:404,{ok:true});return send(res,405,{message:'Método no permitido.'})}catch(e){return send(res,e.status||400,{message:e.message})}}
async function handleClientApi(req,res,pathname){try{if(pathname==='/api/client/login'&&req.method==='POST'){const b=await readBody(req),user=await authenticateClient(b.username,b.password);if(!user)return send(res,401,{message:'Usuario o contraseña incorrectos, o cliente no activo.'});const s=await createClientSession(user,user.username);return send(res,200,{client:publicClient(user),expiresAt:s.expiresAt},{'Set-Cookie':clientSessionCookie(s.token)})}if(pathname==='/api/client/me'&&req.method==='GET'){const s=await getClientSession(getClientToken(req));return s?send(res,200,{client:publicClient(s.user)}):send(res,401,{message:'Sesión de cliente no válida o expirada.'})}if(pathname==='/api/client/logout'&&req.method==='POST'){await destroyClientSession(getClientToken(req));return send(res,200,{ok:true},{'Set-Cookie':clearClientSessionCookie()})}if(pathname.startsWith('/api/client/'))return send(res,404,{message:'Ruta de cliente no encontrada.'});return false}catch(e){return send(res,e.status||400,{message:e.message})}}
async function handleStreamApi(req,res,pathname,user){try{if(pathname==='/api/streams'&&req.method==='GET')return send(res,200,{ffmpeg:await assertFfmpeg(),streams:listStreams()});const state=pathname.match(/^\/api\/streams\/([^/]+)$/);if(state&&req.method==='GET')return send(res,200,{stream:getStream(decodeURIComponent(state[1]))});const reset=pathname.match(/^\/api\/streams\/([^/]+)\/history$/);if(reset&&req.method==='DELETE'){const channelId=decodeURIComponent(reset[1]),stream=clearStreamHistory(channelId);await addAudit({action:'STREAM_HISTORY_CLEAR',module:'streaming',actor:user.username,detail:`Canal ${channelId}`,metadata:{channelId}});return send(res,200,{stream})}const action=pathname.match(/^\/api\/streams\/([^/]+)\/(start|stop|restart)$/);if(action&&req.method==='POST'){const channelId=decodeURIComponent(action[1]),name=action[2],stream=name==='start'?await startStream(channelId):name==='stop'?await stopStream(channelId):await restartStream(channelId);return send(res,200,{stream})}return false}catch(e){return send(res,e.status||500,{message:e.message||'No se pudo controlar el stream.'})}}
async function handleUpdateApi(req,res,pathname,user){if(!pathname.startsWith('/api/update'))return false;try{if(pathname==='/api/update/status'&&req.method==='GET')return send(res,200,await getUpdateStatus());if(pathname==='/api/update/install'&&req.method==='POST')return send(res,202,await installUpdate());return send(res,404,{message:'Ruta de actualización no encontrada.'})}catch(e){return send(res,e.status||500,{message:e.message})}}
async function handle(req,res){const url=new URL(req.url,`http://${req.headers.host||'localhost'}`),pathname=url.pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});return res.end()}if(pathname.startsWith('/api/client/')){const x=await handleClientApi(req,res,pathname);if(x!==false)return}if(pathname==='/api/auth/login'&&req.method==='POST'){const b=await readBody(req),result=await authenticate(b.username,b.password,{ip:clientIp(req),userAgent:req.headers['user-agent']||''});if(!result)return send(res,401,{message:'Usuario o contraseña incorrectos.'});return send(res,200,{user:result.user},{'Set-Cookie':serializeSessionCookie(result.token)})}if(pathname==='/api/auth/me'&&req.method==='GET'){const u=await getSessionUser(sessionToken(req));return u?send(res,200,{user:u}):send(res,401,{message:'No autenticado.'})}if(pathname==='/api/auth/logout'&&req.method==='POST'){await destroySession(sessionToken(req));return send(res,200,{ok:true},{'Set-Cookie':clearSessionCookie()})}if(pathname==='/api/health')return proxyRequest(req,res);const user=await getSessionUser(sessionToken(req));if(!user)return send(res,401,{message:'Autenticación requerida.'});if(pathname.startsWith('/api/update')){if(!hasPermission(user,'system.update'))return send(res,403,{message:'No tienes permiso para actualizar IPZStream.'});const x=await handleUpdateApi(req,res,pathname,user);if(x!==false)return}if(pathname==='/api/source-probe'&&req.method==='POST'){if(!hasPermission(user,'channels.update'))return send(res,403,{message:'No tienes permiso para probar fuentes.'});try{return send(res,200,{result:await probeSource(await readBody(req))})}catch(e){return send(res,e.status||400,{message:e.message})}}if(pathname.startsWith('/streams/')){const x=await handleHls(req,res,pathname);if(x!==false)return}const permission=pathname.startsWith('/api/streams')?(req.method==='GET'?'channels.view':'channels.update'):permissionForRequest(req.method,pathname);if(permission&&!hasPermission(user,permission))return send(res,403,{message:'No tienes permiso para realizar esta acción.',permission});if(pathname.startsWith('/api/streams')){const x=await handleStreamApi(req,res,pathname,user);if(x!==false)return}if(pathname==='/api/users'||pathname.startsWith('/api/users/'))return handleUserApi(req,res,user);let body=null;if(req.method!=='GET'&&req.method!=='HEAD'){const chunks=[];for await(const chunk of req)chunks.push(chunk);body=Buffer.concat(chunks)}proxyRequest(req,res,body)}
await ensureAuthSchema();await ensureUserSchema();await ensureClientSessionSchema();process.env.IPZTREAM_API_PORT=String(INTERNAL_PORT);await import('./index.js');http.createServer((req,res)=>handle(req,res).catch(e=>send(res,500,{message:e.message||'Error interno.'}))).listen(PUBLIC_PORT,HOST,()=>console.log(`IPZStream Secure API escuchando en http://${HOST}:${PUBLIC_PORT}; API interna en ${INTERNAL_PORT}`));
