import React from 'react';
import { Save, X } from 'lucide-react';

const empty={name:'',ip:'',region:'',status:'En línea',cpu:'',ram:'',capacity:''};
export default function NodeForm({onCancel,onSave}){
 const [form,setForm]=React.useState(empty),[error,setError]=React.useState('');
 const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 const submit=e=>{e.preventDefault();setError('');if(!form.name.trim()||!form.ip.trim()||!form.region.trim()||!form.capacity.trim()){setError('Nombre, IP, región y capacidad son obligatorios.');return;}if(!/^((25[0-5]|2[0-4]\d|1?\d?\d)\.){3}(25[0-5]|2[0-4]\d|1?\d?\d)$/.test(form.ip.trim())){setError('Ingresa una dirección IPv4 válida.');return;}const ok=onSave({...form,name:form.name.trim(),ip:form.ip.trim(),region:form.region.trim(),capacity:form.capacity.trim(),cpu:form.cpu===''?null:Math.max(0,Math.min(100,Number(form.cpu))),ram:form.ram===''?null:Math.max(0,Math.min(100,Number(form.ram)))});if(ok===false)return;};
 return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><h2>Agregar nodo</h2><p>Registra un servidor de streaming para el panel.</p></div><button type="button" className="icon-button" onClick={onCancel}><X size={18}/></button></div>{error&&<div className="form-error">{error}</div>}<div className="form-grid node-form-grid"><label>Nombre del nodo<input autoFocus value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Nodo 06 - Cusco"/></label><label>Dirección IP<input value={form.ip} onChange={e=>set('ip',e.target.value)} placeholder="192.168.10.26"/></label><label>Región<input value={form.region} onChange={e=>set('region',e.target.value)} placeholder="Cusco"/></label><label>Estado<select value={form.status} onChange={e=>set('status',e.target.value)}><option>En línea</option><option>Fuera de línea</option></select></label><label>CPU (%)<input type="number" min="0" max="100" value={form.cpu} onChange={e=>set('cpu',e.target.value)} placeholder="0 - 100"/></label><label>RAM (%)<input type="number" min="0" max="100" value={form.ram} onChange={e=>set('ram',e.target.value)} placeholder="0 - 100"/></label><label>Capacidad<input value={form.capacity} onChange={e=>set('capacity',e.target.value)} placeholder="10 Gbps"/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancelar</button><button type="submit" className="primary-button"><Save size={15}/>Guardar</button></div></form></div>;
}
