// IPZStream main shell — 2026-09-15
// Update: connects the existing Actualizar button to the modular real update center.
// Receives navigation/UI state and delegates update operations to src/modules/system-update/UpdateCenter.jsx.

import React from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, BarChart3, Bell, CalendarDays, Database, Home, ListVideo, Menu, Package, PlaySquare, Radio, Search, Server, Settings as SettingsIcon, Smartphone, Users as UsersIcon, X, ChevronDown } from 'lucide-react';
import UsersPage from './modules/users/Users.jsx';
import SettingsPage from './modules/settings/Settings.jsx';
import ChannelsPage from './modules/channels/Channels.jsx';
import VodPage from './modules/vod/Vod.jsx';
import EpgPage from './modules/epg/Epg.jsx';
import M3uPage from './modules/m3u/M3u.jsx';
import PackagesPage from './modules/packages/Packages.jsx';
import ConnectionsPage from './modules/connections/Connections.jsx';
import DevicesPage from './modules/devices/Devices.jsx';
import LogsPage from './modules/logs/Logs.jsx';
import StatisticsPage from './modules/statistics/Statistics.jsx';
import UpdateCenter from './modules/system-update/UpdateCenter.jsx';
import './styles.css';

const nav=[['Dashboard','dashboard',Home],['Usuarios','users',UsersIcon],['Servidores / Nodos','nodes',Server],['Canales','channels',Radio],['VOD / Series','vod',PlaySquare],['EPG','epg',CalendarDays],['Listas M3U','m3u',ListVideo],['Paquetes / Perfiles','packages',Package],['Conexiones Activas','connections',Activity],['Dispositivos','devices',Smartphone],['Logs / Auditoría','logs',FileTextIcon],['Estadísticas','stats',BarChart3],['Configuración','settings',SettingsIcon]];
function FileTextIcon(){return <span style={{fontSize:16,lineHeight:1}}>▤</span>}
const seed={users:[['cliente01','Cliente 01','Activo','Premium','2','30/10/2026'],['cliente02','Cliente 02','Activo','Básico','1','15/11/2026'],['cliente03','Cliente 03','Suspendido','Premium','0','02/09/2026'],['cliente04','Cliente 04','Activo','Familia','3','12/12/2026']],nodes:[['Nodo 01 - Lima','En línea','192.168.10.21','22%','41%','10 Gbps'],['Nodo 02 - Arequipa','En línea','192.168.10.22','18%','36%','10 Gbps'],['Nodo 03 - Trujillo','En línea','192.168.10.23','27%','48%','5 Gbps'],['Nodo 05 - Piura','Fuera de línea','192.168.10.25','—','—','5 Gbps']],channels:[['ESPN','Deportes','Activo','HD','Nodo 01'],['HBO Max','Entretenimiento','Activo','FHD','Nodo 02'],['TUDN','Deportes','Activo','HD','Nodo 01']],vod:[['Película de prueba','Película','Activo','2026','1080p'],['La Serie IPZ','Serie','Activo','T1 · 8 eps.','1080p']],epg:[['ESPN','Fútbol Internacional','13/09 18:00','13/09 20:00','Programado'],['HBO Max','Película Prime','13/09 20:00','13/09 22:00','Programado']],m3u:[['Lista Premium','Premium','Activo','1,024','30 días'],['Lista Básica','Básico','Activo','512','15 días']],packages:[['Básico','1 conexión','512 canales','Activo','$ 10.00'],['Premium','3 conexiones','1,024 canales','Activo','$ 20.00'],['Familia','5 conexiones','1,024 + VOD','Activo','$ 35.00']],connections:[['cliente01','Smart TV Samsung','192.168.1.45','ESPN','Nodo 01','14:28','Activo'],['cliente02','Android TV','192.168.1.78','HBO Max','Nodo 02','14:26','Activo'],['cliente03','Fire TV','192.168.1.92','Discovery','Nodo 03','14:24','Activo']]};
const cols={users:['Usuario','Nombre','Estado','Paquete','Conexiones','Vencimiento'],nodes:['Nodo','Estado','IP','CPU','RAM','Capacidad'],channels:['Canal','Categoría','Estado','Calidad','Nodo'],vod:['Contenido','Tipo','Estado','Temporada / Año','Calidad'],epg:['Canal','Programa','Inicio','Fin','Estado'],m3u:['Lista','Perfil','Estado','Elementos','Vigencia'],packages:['Paquete','Conexiones','Contenido','Estado','Precio'],connections:['Usuario','Dispositivo','IP','Canal / Contenido','Nodo','Hora','Estado']};
function Kpi({icon:Icon,title,value,trend,tone}){return <div className="kpi-card"><div className={`kpi-icon ${tone}`}><Icon size={23}/></div><div><div className="kpi-title">{title}</div><div className="kpi-value">{value}</div><div className="kpi-trend"><span>↑ {trend}</span><small>vs. mes anterior</small></div></div></div>}
function Dashboard({go}){return <><div className="page-heading"><div><h1>Dashboard</h1><p>Centro de control y monitoreo de IPZStream</p></div><div className="date"><CalendarDays size={17}/><div><strong>13 de septiembre de 2026</strong><span>14:32 (GMT-05:00)</span></div></div></div><div className="kpis"><Kpi icon={UsersIcon} title="Usuarios Activos" value="1,248" trend="12%" tone="blue"/><Kpi icon={PlaySquare} title="Conexiones Activas" value="2,486" trend="8%" tone="green"/><Kpi icon={Server} title="Nodos en Línea" value="4 / 5" trend="0%" tone="purple"/><Kpi icon={Database} title="Ingresos (Este mes)" value="$ 3,482.50" trend="15%" tone="orange"/></div><div className="dashboard-grid"><section className="card bandwidth"><div className="card-head"><h2>Uso de Ancho de Banda</h2></div><div className="chart-wrap"><svg className="line-chart" viewBox="0 0 700 260" preserveAspectRatio="none"><path d="M0 160 C100 180 160 120 235 130 S320 100 350 92 S430 125 470 102 S540 55 585 74 S650 84 700 92" className="series-blue"/><path d="M0 191 C100 200 160 175 235 178 S320 170 350 160 S430 175 470 153 S540 126 585 142 S650 135 700 142" className="series-green"/></svg></div></section><section className="card"><div className="card-head"><h2>Distribución de Contenido</h2></div><div className="distribution"><div className="donut"><div><strong>1,248</strong><span>Total de usuarios</span></div></div><div className="legend"><div>TV en Vivo <b>52%</b></div><div>VOD <b>28%</b></div><div>Series <b>12%</b></div><div>Otros <b>8%</b></div></div></div></section><section className="card nodes"><div className="card-head"><h2>Estado de Nodos</h2><button className="link-button" onClick={()=>go('nodes')}>Ver todos →</button></div>{seed.nodes.map(n=><div className="node" key={n[0]}><div className={`status ${n[1]==='Fuera de línea'?'off':''}`}/><div className="node-name"><strong>{n[0]}</strong><span>{n[1]}</span></div><div className="node-metric">CPU <b>{n[3]}</b></div><div className="node-metric">RAM <b>{n[4]}</b></div></div>)}</section></div></>}
function Settings(){return <SettingsPage/>}
function App(){const [page,setPage]=React.useState('dashboard'),[side,setSide]=React.useState(false),[updates,setUpdates]=React.useState(false);const go=p=>{setPage(p);setSide(false);window.scrollTo({top:0,behavior:'smooth'})};return <div className="app"><aside className={`sidebar ${side?'open':''}`}><div className="brand"><div className="brand-mark"><PlaySquare size={23}/></div><div><strong>IPZSTREAM</strong><span>IPTV Management Platform</span></div></div><button className="mobile-close" onClick={()=>setSide(false)}><X size={20}/></button><nav>{nav.map(([label,id,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}>{typeof Icon==='function'&&Icon.length===0?<Icon/>:<Icon size={17}/>}<span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div>Versión 0.1.0</div><div className="online"><i/> Sistema en línea</div></div></aside>{side&&<div className="backdrop" onClick={()=>setSide(false)}/>}<main className="main"><header className="topbar"><button className="menu-button" onClick={()=>setSide(true)}><Menu size={21}/></button><div className="global-search"><Search size={18}/><span>Buscar usuarios, canales, dispositivos...</span><kbd>Ctrl + K</kbd></div><div className="top-actions"><button className="update-button" onClick={()=>setUpdates(true)} title="Buscar actualizaciones"><span>Actualizar</span></button><Bell size={19}/><span className="bell-dot">3</span><div className="avatar">RA</div><span className="admin">Administrador</span><ChevronDown size={15}/></div></header><section className="content">{page==='dashboard'?<Dashboard go={go}/>:page==='users'?<UsersPage/>:page==='stats'?<StatisticsPage/>:page==='settings'?<Settings/>:page==='logs'?<LogsPage/>:page==='channels'?<ChannelsPage/>:page==='vod'?<VodPage/>:page==='epg'?<EpgPage/>:page==='m3u'?<M3uPage/>:page==='packages'?<PackagesPage/>:page==='connections'?<ConnectionsPage/>:page==='devices'?<DevicesPage/>:<div className="card"><p>Módulo no disponible.</p></div>}</section></main>{updates&&<UpdateCenter close={()=>setUpdates(false)}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
