import React from 'react';
import { createRoot } from 'react-dom/client';
import {
  Activity, BarChart3, Bell, CalendarDays, ChevronDown, ChevronRight, Database, FileText, Home,
  ListVideo, Menu, MoreVertical, Package, PlaySquare, Plus, Radio, RefreshCw, Search, Server,
  Settings, Smartphone, SlidersHorizontal, Trash2, Users, Video, Wifi, X, Edit3, Save, Shield,
  HardDrive, ClipboardList, Gauge, Copy, Eye, EyeOff
} from 'lucide-react';
import './styles.css';

const nav = [
  ['Dashboard', 'dashboard', Home], ['Usuarios', 'users', Users], ['Servidores / Nodos', 'nodes', Server],
  ['Canales', 'channels', Radio], ['VOD / Series', 'vod', PlaySquare], ['EPG', 'epg', CalendarDays],
  ['Listas M3U', 'm3u', ListVideo], ['Paquetes / Perfiles', 'packages', Package],
  ['Conexiones Activas', 'connections', Activity], ['Dispositivos', 'devices', Smartphone],
  ['Logs / Auditoría', 'logs', FileText], ['Estadísticas', 'stats', BarChart3], ['Configuración', 'settings', Settings]
];

const pageMeta = {
  users: { title: 'Usuarios', subtitle: 'Gestiona clientes, cuentas, paquetes y vencimientos.', icon: Users, action: 'Nuevo usuario', search: 'Buscar usuario...', filters: ['Estado', 'Paquete'] },
  nodes: { title: 'Servidores / Nodos', subtitle: 'Administra los servidores de streaming y su estado.', icon: Server, action: 'Agregar nodo', search: 'Buscar nodo...', filters: ['Estado', 'Región'] },
  channels: { title: 'Canales', subtitle: 'Gestiona canales en vivo y sus fuentes de señal.', icon: Radio, action: 'Nuevo canal', search: 'Buscar canal...', filters: ['Estado', 'Categoría'] },
  vod: { title: 'VOD / Series', subtitle: 'Organiza películas, series y contenido bajo demanda.', icon: PlaySquare, action: 'Agregar contenido', search: 'Buscar contenido...', filters: ['Tipo', 'Estado'] },
  epg: { title: 'EPG', subtitle: 'Programa y administra la guía electrónica de programación.', icon: CalendarDays, action: 'Agregar programación', search: 'Buscar programa...', filters: ['Canal', 'Fecha'] },
  m3u: { title: 'Listas M3U', subtitle: 'Controla listas, fuentes y accesos de reproducción.', icon: ListVideo, action: 'Nueva lista', search: 'Buscar lista...', filters: ['Estado', 'Perfil'] },
  packages: { title: 'Paquetes / Perfiles', subtitle: 'Define planes, límites y permisos de contenido.', icon: Package, action: 'Nuevo paquete', search: 'Buscar paquete...', filters: ['Estado'] },
  connections: { title: 'Conexiones Activas', subtitle: 'Supervisa sesiones y consumo en tiempo real.', icon: Activity, action: 'Actualizar sesiones', search: 'Buscar usuario, IP...', filters: ['Nodo', 'Estado'] },
  devices: { title: 'Dispositivos', subtitle: 'Controla equipos autorizados y sus sesiones.', icon: Smartphone, action: 'Registrar dispositivo', search: 'Buscar dispositivo...', filters: ['Estado', 'Tipo'] },
  logs: { title: 'Logs / Auditoría', subtitle: 'Consulta actividad administrativa y eventos del sistema.', icon: FileText, action: null, search: 'Buscar evento...', filters: ['Nivel', 'Módulo'] },
  stats: { title: 'Estadísticas', subtitle: 'Analiza usuarios, conexiones, tráfico y rendimiento.', icon: BarChart3, action: 'Actualizar datos', search: null, filters: ['Periodo'] },
  settings: { title: 'Configuración', subtitle: 'Ajusta parámetros generales y preferencias de IPZStream.', icon: Settings, action: 'Guardar cambios', search: null, filters: [] }
};

const seed = {
  users: [
    ['cliente01', 'Cliente 01', 'Activo', 'Premium', '2', '30/10/2026'], ['cliente02', 'Cliente 02', 'Activo', 'Básico', '1', '15/11/2026'],
    ['cliente03', 'Cliente 03', 'Suspendido', 'Premium', '0', '02/09/2026'], ['cliente04', 'Cliente 04', 'Activo', 'Familia', '3', '12/12/2026'],
    ['cliente05', 'Cliente 05', 'Activo', 'Premium', '1', '18/10/2026'], ['cliente06', 'Cliente 06', 'Vencido', 'Básico', '0', '01/09/2026']
  ],
  nodes: [['Nodo 01 - Lima','En línea','192.168.10.21','22%','41%','10 Gbps'],['Nodo 02 - Arequipa','En línea','192.168.10.22','18%','36%','10 Gbps'],['Nodo 03 - Trujillo','En línea','192.168.10.23','27%','48%','5 Gbps'],['Nodo 04 - Cusco','En línea','192.168.10.24','31%','55%','5 Gbps'],['Nodo 05 - Piura','Fuera de línea','192.168.10.25','—','—','5 Gbps']],
  channels: [['ESPN','Deportes','Activo','HD','Nodo 01'],['HBO Max','Entretenimiento','Activo','FHD','Nodo 02'],['Discovery Channel','Documentales','Activo','HD','Nodo 03'],['TUDN','Deportes','Activo','HD','Nodo 01'],['Canal IPZ','General','Inactivo','FHD','Nodo 04']],
  vod: [['Película de prueba','Película','Activo','2026','1080p'],['La Serie IPZ','Serie','Activo','T1 · 8 eps.','1080p'],['Documental Perú','Película','Activo','2025','4K'],['Serie Demo','Serie','Inactivo','T2 · 10 eps.','720p']],
  epg: [['ESPN','Fútbol Internacional','13/09 18:00','13/09 20:00','Programado'],['HBO Max','Película Prime','13/09 20:00','13/09 22:00','Programado'],['Discovery Channel','Documentales','13/09 19:00','13/09 21:00','En curso']],
  m3u: [['Lista Premium','Premium','Activo','1,024','30 días'],['Lista Básica','Básico','Activo','512','15 días'],['Lista Prueba','Demo','Inactivo','50','7 días']],
  packages: [['Básico','1 conexión','512 canales','Activo','$ 10.00'],['Premium','3 conexiones','1,024 canales','Activo','$ 20.00'],['Familia','5 conexiones','1,024 + VOD','Activo','$ 35.00']],
  connections: [['cliente01','Smart TV Samsung','192.168.1.45','ESPN','Nodo 01','14:28','Activo'],['cliente02','Android TV','192.168.1.78','HBO Max','Nodo 02','14:26','Activo'],['cliente03','Fire TV','192.168.1.92','Discovery Channel','Nodo 03','14:24','Activo'],['cliente04','iPhone','192.168.1.103','TUDN','Nodo 01','14:22','Activo'],['cliente05','Web Player','190.235.12.45','VOD - Película','Nodo 04','14:20','Activo']],
  devices: [['Smart TV Samsung','cliente01','TV','192.168.1.45','Activo','14:28'],['Android TV Box','cliente02','TV Box','192.168.1.78','Activo','14:26'],['Fire TV Stick','cliente03','Streaming','192.168.1.92','Activo','14:24'],['iPhone 15','cliente04','Móvil','192.168.1.103','Activo','14:22'],['Web Player','cliente05','Web','190.235.12.45','Inactivo','Ayer']],
  logs: [['14:32:10','INFO','Usuarios','Inicio de sesión administrativo','admin'],['14:30:42','INFO','Nodos','Heartbeat recibido de Nodo 03','system'],['14:28:19','WARN','Conexiones','Límite de conexión alcanzado: cliente01','system'],['14:22:08','INFO','Canales','Canal TUDN actualizado','admin'],['14:15:31','ERROR','Nodos','Nodo 05 no responde','system']]
};

const columns = {
  users: ['Usuario','Nombre','Estado','Paquete','Conexiones','Vencimiento'], nodes: ['Nodo','Estado','IP','CPU','RAM','Capacidad'],
  channels: ['Canal','Categoría','Estado','Calidad','Nodo'], vod: ['Contenido','Tipo','Estado','Temporada / Año','Calidad'],
  epg: ['Canal','Programa','Inicio','Fin','Estado'], m3u: ['Lista','Perfil','Estado','Elementos','Vigencia'],
  packages: ['Paquete','Conexiones','Contenido','Estado','Precio'], connections: ['Usuario','Dispositivo','IP','Canal / Contenido','Nodo','Hora','Estado'],
  devices: ['Dispositivo','Usuario','Tipo','IP','Estado','Última actividad'], logs: ['Hora','Nivel','Módulo','Evento','Usuario']
};

function statusClass(value='') { return /activo|en línea|en curso|programado|info/i.test(value) ? 'success' : /error|fuera|vencido/i.test(value) ? 'danger' : /warn|suspendido|inactivo/i.test(value) ? 'warning' : ''; }

function Kpi({ icon: Icon, title, value, trend, tone }) { return <div className="kpi-card"><div className={`kpi-icon ${tone}`}><Icon size={23}/></div><div><div className="kpi-title">{title}</div><div className="kpi-value">{value}</div><div className="kpi-trend"><span>↑ {trend}</span><small>vs. mes anterior</small></div></div></div>; }

function Dashboard({ go }) {
  const nodes = [['Nodo 01 - Lima','En línea','22%','41%'],['Nodo 02 - Arequipa','En línea','18%','36%'],['Nodo 03 - Trujillo','En línea','27%','48%'],['Nodo 04 - Cusco','En línea','31%','55%'],['Nodo 05 - Piura','Fuera de línea','—','—']];
  return <>
    <div className="page-heading"><div><h1>Dashboard</h1><p>Centro de control y monitoreo de IPZStream</p></div><div className="date"><CalendarDays size={17}/><div><strong>13 de septiembre de 2026</strong><span>14:32 (GMT-05:00)</span></div></div></div>
    <div className="kpis"><Kpi icon={Users} title="Usuarios Activos" value="1,248" trend="12%" tone="blue"/><Kpi icon={PlaySquare} title="Conexiones Activas" value="2,486" trend="8%" tone="green"/><Kpi icon={Server} title="Nodos en Línea" value="4 / 5" trend="0%" tone="purple"/><Kpi icon={Database} title="Ingresos (Este mes)" value="$ 3,482.50" trend="15%" tone="orange"/></div>
    <div className="dashboard-grid"><section className="card bandwidth"><div className="card-head"><h2>Uso de Ancho de Banda</h2><div className="chart-legend"><span><i className="blue-line"/>Entrada</span><span><i className="green-line"/>Salida</span></div></div><BandwidthChart/></section><section className="card"><div className="card-head"><h2>Distribución de Contenido</h2></div><Distribution/></section><section className="card nodes"><div className="card-head"><h2>Estado de Nodos</h2><button className="link-button" onClick={() => go('nodes')}>Ver todos →</button></div>{nodes.map(n=><div className="node" key={n[0]}><div className={`status ${n[1]==='Fuera de línea'?'off':''}`}/><div className="node-name"><strong>{n[0]}</strong><span className={n[1]==='Fuera de línea'?'red':''}>{n[1]}</span></div><div className="node-metric">CPU <b>{n[2]}</b></div><div className="node-metric">RAM <b>{n[3]}</b></div></div>)}</section></div>
    <section className="card recent"><div className="card-head"><h2>Últimas Conexiones</h2><button className="link-button" onClick={()=>go('connections')}>Ver todas →</button></div><div className="table-scroll"><table><thead><tr><th>Usuario</th><th>Dispositivo</th><th>IP</th><th>Canal / Contenido</th><th>Nodo</th><th>Hora</th><th/></tr></thead><tbody>{seed.connections.map(c=><tr key={c[0]}><td><span className="user-avatar"><Users size={13}/></span><b>{c[0]}</b></td><td>{c[1]}</td><td className="mono">{c[2]}</td><td>{c[3]}</td><td>{c[4]}</td><td>{c[5]}</td><td><span className="live-dot"/><MoreVertical size={15}/></td></tr>)}</tbody></table></div></section>
  </>;
}

function BandwidthChart(){return <div className="chart-wrap"><div className="chart-axis"><span>800 Mbps</span><span>600 Mbps</span><span>400 Mbps</span><span>200 Mbps</span><span>0 Mbps</span></div><svg className="line-chart" viewBox="0 0 700 260" preserveAspectRatio="none"><defs><linearGradient id="areaBlue" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopOpacity=".30"/><stop offset="1" stopOpacity="0"/></linearGradient></defs>{[35,82,129,176,223].map(y=><line key={y} x1="0" x2="700" y1={y} y2={y} className="grid-line"/>)}<path d="M0 160 C60 168 70 170 115 156 S190 125 235 130 S300 132 350 92 S420 120 470 102 S540 55 585 74 S650 84 700 92 L700 223 L0 223 Z" className="area-blue"/><path d="M0 160 C60 168 70 170 115 156 S190 125 235 130 S300 132 350 92 S420 120 470 102 S540 55 585 74 S650 84 700 92" className="series-blue"/><path d="M0 191 C60 193 80 188 115 189 S190 171 235 178 S300 175 350 160 S420 171 470 153 S540 126 585 142 S650 135 700 142" className="series-green"/></svg><div className="chart-labels"><span>6 Sep</span><span>7 Sep</span><span>8 Sep</span><span>9 Sep</span><span>10 Sep</span><span>11 Sep</span><span>12 Sep</span><span>13 Sep</span></div></div>}
function Distribution(){return <div className="distribution"><div className="donut"><div><strong>1,248</strong><span>Total de usuarios</span></div></div><div className="legend"><div><i className="dot blue"/>TV en Vivo <b>52%</b></div><div><i className="dot purple"/>VOD <b>28%</b></div><div><i className="dot green"/>Series <b>12%</b></div><div><i className="dot orange"/>Otros <b>8%</b></div></div></div>}

function ModulePage({ type, rows, setRows }) {
  const meta = pageMeta[type]; const Icon = meta.icon; const cols = columns[type] || [];
  const [query,setQuery] = React.useState(''); const [filter,setFilter] = React.useState('Todos'); const [modal,setModal] = React.useState(false); const [menu,setMenu] = React.useState(null);
  const filtered = rows.filter(r => r.join(' ').toLowerCase().includes(query.toLowerCase()) && (filter==='Todos' || r.some(x=>x===filter)));
  const add = () => { const value = window.prompt(`Nombre para ${meta.title.toLowerCase()}:`); if(value) setRows([[value,'Nuevo','Activo',...Array(Math.max(cols.length-2,0)).fill('—')],...rows]); setModal(false); };
  const remove = (index) => { if(window.confirm('¿Eliminar este registro?')) setRows(rows.filter((_,i)=>i!==index)); setMenu(null); };
  return <div className="module-page"><div className="module-head"><div className="module-title"><div className="module-icon"><Icon size={22}/></div><div><h1>{meta.title}</h1><p>{meta.subtitle}</p></div></div>{meta.action && <button className="primary-button" onClick={type==='stats'?undefined:()=>setModal(true)}><Plus size={16}/>{meta.action}</button>}</div>
    <div className="toolbar"><div className="module-search">{meta.search && <><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={meta.search}/></>}</div><div className="filters">{meta.filters.map(f=><button key={f} className="filter-button"><SlidersHorizontal size={13}/>{f}<ChevronDown size={13}/></button>)}{meta.filters.length>0&&<button className="filter-button" onClick={()=>setFilter(filter==='Todos'?'Activo':'Todos')}>Estado: {filter}</button>}</div></div>
    <div className="card module-table"><div className="table-info"><span>{filtered.length} registros</span><span>Actualizado hace unos segundos</span></div><div className="table-scroll"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}<th>Acciones</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={`${r[0]}-${i}`}>{r.map((cell,j)=><td key={j}>{j===2 && type!=='nodes' || (type==='nodes'&&j===1) || (type==='logs'&&j===1) ? <span className={`status-badge ${statusClass(cell)}`}>{cell}</span> : cell}</td>)}<td className="actions-cell"><button className="icon-button" onClick={()=>setMenu(menu===i?null:i)}><MoreVertical size={16}/></button>{menu===i&&<div className="row-menu"><button><Edit3 size={14}/>Editar</button><button><Eye size={14}/>Ver detalle</button><button className="danger-text" onClick={()=>remove(rows.indexOf(r))}><Trash2 size={14}/>Eliminar</button></div>}</td></tr>)}</tbody></table></div></div>
    {modal&&<Modal title={meta.action} onClose={()=>setModal(false)} onSave={add}/>} 
  </div>;
}

function Modal({title,onClose,onSave}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label>Nombre<input autoFocus placeholder="Escribe un nombre..." id="quick-name"/></label><label>Estado<select><option>Activo</option><option>Inactivo</option></select></label><label>Descripción<textarea placeholder="Descripción opcional"/></label></div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={()=>{const el=document.getElementById('quick-name'); if(el?.value.trim()) onSave();}}><Save size={15}/>Guardar</button></div></div></div>}

function Stats(){return <div className="module-page"><div className="module-head"><div className="module-title"><div className="module-icon"><BarChart3 size={22}/></div><div><h1>Estadísticas</h1><p>Indicadores generales para supervisar la plataforma.</p></div></div><button className="primary-button" onClick={()=>window.location.reload()}><RefreshCw size={15}/>Actualizar datos</button></div><div className="stat-grid"><div className="stat-big"><span>Usuarios registrados</span><strong>3,842</strong><small>+14.2% este mes</small></div><div className="stat-big"><span>Horas de reproducción</span><strong>18,492 h</strong><small>+8.4% este mes</small></div><div className="stat-big"><span>Tráfico generado</span><strong>42.8 TB</strong><small>+11.7% este mes</small></div><div className="stat-big"><span>Disponibilidad</span><strong>99.92%</strong><small>Últimos 30 días</small></div><div className="card stat-chart"><div className="card-head"><h2>Conexiones por hora</h2></div><div className="bars">{[34,48,42,63,72,58,84,69,91,78,64,52,45,57,71,88,76,62].map((v,i)=><div key={i} style={{height:`${v}%`}}><span>{v*30}</span></div>)}</div></div><div className="card health"><div className="card-head"><h2>Salud del sistema</h2></div><Health label="API" value="100%"/><Health label="Nodos" value="98.7%"/><Health label="Base de datos" value="100%"/><Health label="Almacenamiento" value="76%"/></div></div></div>}
function Health({label,value}){return <div className="health-row"><span>{label}</span><b>{value}</b><div><i style={{width:value}}/></div></div>}

function SettingsPage(){const [saved,setSaved]=React.useState(false);return <div className="module-page"><div className="module-head"><div className="module-title"><div className="module-icon"><Settings size={22}/></div><div><h1>Configuración</h1><p>Parámetros generales del panel IPZStream.</p></div></div><button className="primary-button" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}}><Save size={15}/>{saved?'Guardado':'Guardar cambios'}</button></div><div className="settings-grid"><section className="card settings-card"><h2>General</h2><label>Nombre de la plataforma<input defaultValue="IPZStream"/></label><label>Zona horaria<select defaultValue="America/Lima"><option value="America/Lima">America/Lima (GMT-05:00)</option></select></label><label>URL del panel<input defaultValue="http://192.168.10.220"/></label></section><section className="card settings-card"><h2>Seguridad</h2><Toggle label="Forzar HTTPS"/><Toggle label="Protección contra fuerza bruta" enabled/><Toggle label="Registrar auditoría" enabled/><Toggle label="Sesiones múltiples" enabled/></section><section className="card settings-card"><h2>Actualizaciones</h2><div className="version-box"><div><span>Versión instalada</span><strong>0.1.0</strong></div><span className="status-badge success">Actualizada</span></div><p className="muted">El botón de actualización del encabezado está preparado para integrarse posteriormente con el updater y releases firmados.</p></section></div></div>}
function Toggle({label,enabled=false}){const [on,setOn]=React.useState(enabled);return <button className={`toggle-row ${on?'on':''}`} onClick={()=>setOn(!on)}><span>{label}</span><i><b/></i></button>}

function App(){const [sidebar,setSidebar]=React.useState(false);const [page,setPage]=React.useState('dashboard');const [rows,setRows]=React.useState(seed);const meta=pageMeta[page];const go=p=>{setPage(p);setSidebar(false);window.scrollTo({top:0,behavior:'smooth'})};const handleUpdate=()=>window.location.reload();
 return <div className="app"><aside className={`sidebar ${sidebar?'open':''}`}><div className="brand"><div className="brand-mark"><PlaySquare size={23}/></div><div><strong>IPZSTREAM</strong><span>IPTV Management Platform</span></div></div><button className="mobile-close" onClick={()=>setSidebar(false)}><X size={20}/></button><nav>{nav.map(([label,id,Icon])=><button className={page===id?'active':''} key={id} onClick={()=>go(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div>Versión 0.1.0</div><div className="online"><i/> Sistema en línea</div></div></aside>{sidebar&&<div className="backdrop" onClick={()=>setSidebar(false)}/>}<main className="main"><header className="topbar"><button className="menu-button" onClick={()=>setSidebar(true)}><Menu size={21}/></button><div className="global-search"><Search size={18}/><span>Buscar usuarios, canales, dispositivos...</span><kbd>Ctrl + K</kbd></div><div className="top-actions"><button className="update-button" onClick={handleUpdate} title="Actualizar panel"><RefreshCw size={15}/><span>Actualizar</span></button><Bell size={19}/><span className="bell-dot">3</span><div className="avatar">RA</div><span className="admin">Administrador</span><ChevronDown size={15}/></div></header><section className="content">{page==='dashboard'?<Dashboard go={go}/>:page==='stats'?<Stats/>:page==='settings'?<SettingsPage/>:<ModulePage type={page} rows={rows[page]} setRows={next=>setRows({...rows,[page]:next})}/>}</section></main></div>}

createRoot(document.getElementById('root')).render(<App/>);
