// IPZStream main shell — 2026-09-15
// Update: connects the existing Actualizar button to the modular real update center.
// Receives navigation/UI state and delegates update operations to src/modules/system-update/UpdateCenter.jsx.

import React from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, BarChart3, Bell, CalendarDays, Database, Home, ListVideo, Menu, Package, PlaySquare, Radio, Search, Server, Settings as SettingsIcon, Smartphone, Users as UsersIcon, X, ChevronDown, Layers3, Tv2, Film, UserCog, HardDrive, ScrollText, Wrench, CircleDollarSign } from 'lucide-react';
import UsersPage from './modules/users/Users.jsx';
import SettingsPage from './modules/settings/Settings.jsx';
import ChannelsPage from './modules/channels/Channels.jsx';
import VodPage from './modules/vod/Vod.jsx';
import EpgPage from './modules/epg/Epg.jsx';
import M3uPage from './modules/m3u/M3u.jsx';
import PackagesPage from './modules/packages/Packages.jsx';
import ConnectionsPage from './modules/connections/Connections.jsx';
import DevicesPage from './modules/devices/Devices.jsx';
import LogsPage from './modules/logs/Logs.jsx';
import StatisticsPage from './modules/statistics/Statistics.jsx';
import UpdateCenter from './modules/system-update/UpdateCenter.jsx';
import './styles.css';

const navGroups=[
  ['GENERAL',[['Dashboard','dashboard',Home],['Actividad / Conexiones','connections',Activity],['Estadísticas','stats',BarChart3]]],
  ['CONTENIDO',[['Streams / Canales','channels',Radio],['VOD / Películas','vod',Film],['Series','vod',Tv2],['EPG','epg',CalendarDays],['Listas M3U','m3u',ListVideo],['Bouquets / Paquetes','packages',Layers3]]],
  ['GESTIÓN',[['Líneas / Usuarios','users',UsersIcon],['Resellers','users',UserCog],['Dispositivos / MAG','devices',Smartphone],['Servidores','nodes',Server]]],
  ['SISTEMA',[['Logs','logs',ScrollText],['Backups / Herramientas','settings',HardDrive],['Configuración','settings',SettingsIcon]]]
];
function FileTextIcon(){return <span style={{fontSize:16,lineHeight:1}}>▤</span>}
const seed={users:[['cliente01','Cliente 01','Activo','Premium','2','30/10/2026'],['cliente02','Cliente 02','Activo','Básico','1','15/11/2026'],['cliente03','Cliente 03','Suspendido','Premium','0','02/09/2026'],['cliente04','Cliente 04','Activo','Familia','3','12/12/2026']],nodes:[['Nodo 01 - Lima','En línea','192.168.10.21','22%','41%','10 Gbps'],['Nodo 02 - Arequipa','En línea','192.168.10.22','18%','36%','10 Gbps'],['Nodo 03 - Trujillo','En línea','192.168.10.23','27%','48%','5 Gbps'],['Nodo 05 - Piura','Fuera de línea','192.168.10.25','—','—','5 Gbps']],channels:[['ESPN','Deportes','Activo','HD','Nodo 01'],['HBO Max','Entretenimiento','Activo','FHD','Nodo 02'],['TUDN','Deportes','Activo','HD','Nodo 01']],vod:[['Película de prueba','Película','Activo','2026','1080p'],['La Serie IPZ','Serie','Activo','T1 · 8 eps.','1080p']],epg:[['ESPN','Fútbol Internacional','13/09 18:00','13/09 20:00','Programado'],['HBO Max','Película Prime','13/09 20:00','13/09 22:00','Programado']],m3u:[['Lista Premium','Premium','Activo','1,024','30 días'],['Lista Básica','Básico','Activo','512','15 días']],packages:[['Básico','1 conexión','512 canales','Activo','$ 10.00'],['Premium','3 conexiones','1,024 canales','Activo','$ 20.00'],['Familia','5 conexiones','1,024 + VOD','Activo','$ 35.00']],connections:[['cliente01','Smart TV Samsung','192.168.1.45','ESPN','Nodo 01','14:28','Activo'],['cliente02','Android TV','192.168.1.78','HBO Max','Nodo 02','14:26','Activo'],['cliente03','Fire TV','192.168.1.92','Discovery','Nodo 03','14:24','Activo']]};
const cols={users:['Usuario','Nombre','Estado','Paquete','Conexiones','Vencimiento'],nodes:['Nodo','Estado','IP','CPU','RAM','Capacidad'],channels:['Canal','Categoría','Estado','Calidad','Nodo'],vod:['Contenido','Tipo','Estado','Temporada / Año','Calidad'],epg:['Canal','Programa','Inicio','Fin','Estado'],m3u:['Lista','Perfil','Estado','Elementos','Vigencia'],packages:['Paquete','Conexiones','Contenido','Estado','Precio'],connections:['Usuario','Dispositivo','IP','Canal / Contenido','Nodo','Hora','Estado']};
function Kpi({icon:Icon,title,value,trend,tone}){return <div className="kpi-card"><div className={`kpi-icon ${tone}`}><Icon size={23}/></div><div><div className="kpi-title">{title}</div><div className="kpi-value">{value}</div><div className="kpi-trend"><span>↑ {trend}</span><small>vs. mes anterior</small></div></div></div>}
function Dashboard({go}){const quick=[['Streams',seed.channels.length,Radio,'channels'],['Usuarios',1248,UsersIcon,'users'],['Conexiones',2486,Activity,'connections'],['Servidores','4 / 5',Server,'nodes']];return <div className="legacy-dashboard"><div className="legacy-page-title"><div><h1>Dashboard</h1><p>Bienvenido al panel de administración IPZStream</p></div><span className="legacy-server-time"><Activity size={13}/> Sistema operativo</span></div><div className="legacy-kpis">{quick.map(([label,value,Icon,target])=><button key={label} className="legacy-kpi" onClick={()=>go(target)}><span className="legacy-kpi-icon"><Icon size={25}/></span><span><small>{label}</small><strong>{value}</strong><em>Ver administración →</em></span></button>)}</div><div className="legacy-grid"><section className="legacy-panel"><div className="legacy-panel-head"><strong>Estado del sistema</strong><span>Tiempo real</span></div><div className="legacy-system"><div><span>CPU</span><b>24%</b><i><u style={{width:'24%'}}/></i></div><div><span>Memoria</span><b>46%</b><i><u style={{width:'46%'}}/></i></div><div><span>Red</span><b>1.8 Gbps</b><i><u style={{width:'62%'}}/></i></div><div><span>Streams activos</span><b>98%</b><i><u style={{width:'98%'}}/></i></div></div></section><section className="legacy-panel"><div className="legacy-panel-head"><strong>Accesos rápidos</strong><span>Administración</span></div><div className="legacy-quick"><button onClick={()=>go('channels')}><Radio size={18}/>Administrar Streams</button><button onClick={()=>go('users')}><UsersIcon size={18}/>Administrar Líneas</button><button onClick={()=>go('packages')}><Layers3 size={18}/>Bouquets</button><button onClick={()=>go('epg')}><CalendarDays size={18}/>EPG</button><button onClick={()=>go('nodes')}><Server size={18}/>Servidores</button><button onClick={()=>go('settings')}><Wrench size={18}/>Herramientas</button></div></section></div><section className="legacy-panel legacy-recent"><div className="legacy-panel-head"><strong>Servidores</strong><button onClick={()=>go('nodes')}>Ver todos</button></div><div className="table-scroll"><table><thead><tr><th>Servidor</th><th>Estado</th><th>IP</th><th>CPU</th><th>RAM</th><th>Capacidad</th></tr></thead><tbody>{seed.nodes.map(n=><tr key={n[0]}><td><b>{n[0]}</b></td><td><span className={`legacy-status ${n[1]==='Fuera de línea'?'down':''}`}>{n[1]}</span></td>{n.slice(2).map((x,i)=><td key={i}>{x}</td>)}</tr>)}</tbody></table></div></section></div>}
function Settings(){return <SettingsPage/>}
function App(){const [page,setPage]=React.useState('dashboard'),[side,setSide]=React.useState(false),[updates,setUpdates]=React.useState(false);const go=p=>{setPage(p);setSide(false);window.scrollTo({top:0,behavior:'smooth'})};return <div className="app legacy-app"><aside className={`sidebar legacy-sidebar ${side?'open':''}`}><div className="legacy-brand"><div className="legacy-logo"><PlaySquare size={25}/></div><div><strong>IPZStream</strong><span>Management Panel</span></div></div><button className="mobile-close" onClick={()=>setSide(false)}><X size={20}/></button><nav className="legacy-nav">{navGroups.map(([group,items])=><div className="legacy-nav-group" key={group}><div className="legacy-nav-label">{group}</div>{items.map(([label,id,Icon])=><button key={label} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={16}/><span>{label}</span></button>)}</div>)}</nav><div className="legacy-sidebar-bottom"><span><i/> ONLINE</span><small>IPZStream v0.4.0</small></div></aside>{side&&<div className="backdrop" onClick={()=>setSide(false)}/>}<main className="main legacy-main"><header className="topbar legacy-topbar"><button className="menu-button" onClick={()=>setSide(true)}><Menu size={21}/></button><div className="legacy-top-title"><strong>IPZStream</strong><span>Administrador</span></div><div className="global-search legacy-search"><Search size={16}/><span>Buscar en el panel...</span></div><div className="top-actions"><button className="update-button" onClick={()=>setUpdates(true)}><span>Actualizar</span></button><Bell size={18}/><div className="legacy-admin"><div className="avatar">AD</div><span>Administrador</span><ChevronDown size={14}/></div></div></header><section className="content legacy-content">{page==='dashboard'?<Dashboard go={go}/>:page==='users'?<UsersPage/>:page==='stats'?<StatisticsPage/>:page==='settings'?<Settings/>:page==='logs'?<LogsPage/>:page==='channels'?<ChannelsPage/>:page==='vod'?<VodPage/>:page==='epg'?<EpgPage/>:page==='m3u'?<M3uPage/>:page==='packages'?<PackagesPage/>:page==='connections'?<ConnectionsPage/>:page==='devices'?<DevicesPage/>:<div className="card"><p>Módulo en reconstrucción.</p></div>}</section></main>{updates&&<UpdateCenter close={()=>setUpdates(false)}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
